# -*- coding: utf-8 -*-
"""ANOVA_mixed_lin_wlongformat_final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eckwwG0ah2yCQ-vp4ii_r4mhkv69TuZq

##Codebook
"""

import pandas as pd, numpy as np

# Read CSV-file

df = pd.read_csv('data_long_format.csv')
df['Score'] = [x.replace(',', '.') for x in df['Score']]
df['Score'] = df['Score'].astype(float)

# Check shape (should be 64 rows, 5 columns)

print(df.shape)

!pip install pingouin
import pingouin as pg

# ANOVA

anova_results = pg.rm_anova(data=df, dv="Score",
                  within=["Modality", "Text_type"],
                  subject="Participant_ID",
                  detailed=True)
print(anova_results)

"""#### Interpretation
The modality variance is statistically significant (p = 0.017), meaning that it is easier to recall something that you have read compared to something that you have listened to. No effect for the metaphor/literal condition (text type).

#### Mixed linear model
"""

!pip install statsmodels
import statsmodels.formula.api as smf

# Mixed linear model

df["grp"] = 1
vc = {"participant": "0 + C(Participant_ID)",
      "text":        "0 + C(Base_text)"}

model = smf.mixedlm("Score ~ Modality * Text_type",
                    data=df,
                    groups="grp",
                    vc_formula=vc,
                    re_formula="0").fit(reml=True)

print(model.summary())

# See how much variance is captured by participant, text and residual

vc_p  = model.vcomp[0]                  # participant variance
vc_t  = model.vcomp[1]                  # text variance
vc_e  = model.scale                     # residual variance
tot   = vc_p + vc_t + vc_e
print("\n=== Variance components ===")
for name, v in [("Participant", vc_p), ("Base_text", vc_t), ("Residual", vc_e)]:
    print(f"  {name:11s}: {v:.5f}  ({100*v/tot:4.1f}% of variance, SD={np.sqrt(v):.3f})")

# Inspect means of the conditions

print("\n=== Condition means ===")
print(df.groupby(["Modality","Text_type"])["Score"].mean().round(3))

"""Filtered; without participant 8"""

df = pd.read_csv('data_long_format_filtered.csv')
df['Score'] = [x.replace(',', '.') for x in df['Score']]
df['Score'] = df['Score'].astype(float)
print(df.shape)

anova_results = pg.rm_anova(data=df, dv="Score",
                  within=["Modality", "Text_type"],
                  subject='Participant_ID',
                  detailed=True)
print(anova_results)

df["grp"] = 1
vc = {"participant": "0 + C(Participant_ID)",
      "text":        "0 + C(Base_text)"}

model = smf.mixedlm("Score ~ Modality * Text_type",
                    data=df,
                    groups="grp",
                    vc_formula=vc,
                    re_formula="0").fit(reml=True)

print(model.summary())

# See how much variance is captured by participant, text and residual

vc_p  = model.vcomp[0]                  # participant variance
vc_t  = model.vcomp[1]                  # text variance
vc_e  = model.scale                     # residual variance
tot   = vc_p + vc_t + vc_e
print("\n=== Variance components ===")
for name, v in [("Participant", vc_p), ("Base_text", vc_t), ("Residual", vc_e)]:
    print(f"  {name:11s}: {v:.5f}  ({100*v/tot:4.1f}% of variance, SD={np.sqrt(v):.3f})")

# Inspect means of the conditions

print("\n=== Condition means ===")
print(df.groupby(["Modality","Text_type"])["Score"].mean().round(3))